// Converted MPJE Questions - Ready to paste into App.js
const QUESTIONS = [
  // Set 1: Federal Law & Product Integrity (Q1-24)
  { id: 1, q: "Which 1938 legislation was passed in response to the Sulfanilamide tragedy and required drugs to be proven safe prior to marketing?", o: ["Pure Food and Drug Act", "Kefauver-Harris Amendment", "Food, Drug, and Cosmetic Act (FDCA)", "Durham-Humphrey Amendment"], a: 2 },
  { id: 2, q: "The Durham-Humphrey Amendment of 1951 is best known for which of the following?", o: ["Requiring drugs to be effective", "Creating the distinction between \"Legend\" (Rx) and OTC drugs", "Establishing Good Manufacturing Practices (GMP)", "Regulating drug samples"], a: 1 },
  { id: 3, q: "Which amendment established that drugs must be proven EFFECTIVE in addition to safe?", o: ["Kefauver-Harris Amendment", "Prescription Drug Marketing Act", "Drug Quality and Security Act", "Durham-Humphrey Amendment"], a: 0 },
  { id: 4, q: "Under the Prescription Drug Marketing Act of 1987, who is the only entity allowed to re-import a prescription drug into the U.S.?", o: ["Any licensed wholesaler", "The patient with a valid prescription", "The original manufacturer", "A Class A pharmacy"], a: 2 },
  { id: 5, q: "Generally, retail pharmacies are prohibited from possessing drug samples. Which type of pharmacy is an EXCEPTION to this rule?", o: ["Any Class C Institutional pharmacy", "Pharmacies owned by charitable organizations or government entities serving indigent patients", "Any pharmacy with a specialized storage refrigerator", "Pharmacies located in a medically underserved area"], a: 1 },
  { id: 6, q: "The Drug Compounding Quality Act (DCQA) created Section 503B, which allows a facility to register as an:", o: ["Accredited Compounder", "Institutional Sterile Pharmacy", "Outsourcing Facility", "Traditional Compounding Pharmacy"], a: 2 },
  { id: 7, q: "A 503B Outsourcing Facility is required to follow which quality standard?", o: ["USP <795> only", "USP <797> only", "Current Good Manufacturing Practices (cGMP)", "The individual State Board's manual"], a: 2 },
  { id: 8, q: "Under the DSCSA, how long must a pharmacy maintain \"Transaction Data\" (TI, TH, and TS)?", o: ["2 years", "5 years", "6 years", "10 years"], a: 2 },
  { id: 9, q: "If a pharmacy identifies an \"illegitimate product,\" they must notify the FDA (via Form 3911) and trading partners within:", o: ["12 hours", "24 hours", "48 hours", "72 hours"], a: 1 },
  { id: 10, q: "A drug is stored in a room where the temperature is not adequately controlled. This drug is legally considered:", o: ["Misbranded", "Adulterated", "Misbranded and Adulterated", "Neither, until the drug physically degrades"], a: 1 },
  { id: 11, q: "A pharmacist dispenses a prescription without a valid order from a practitioner. This is a violation known as:", o: ["Adulteration", "Misbranding", "Fraud", "Substitution"], a: 1 },
  { id: 12, q: "If a pharmacist misfills a prescription by providing the wrong strength (e.g., 20mg instead of 10mg), the drug is legally classified as:", o: ["Adulterated only", "Misbranded only", "Both Adulterated and Misbranded", "Neither, provided the patient is not harmed"], a: 2 },
  { id: 13, q: "A manufacturer bottle of tablets does not bear the federal legend \"Rx Only.\" This product is:", o: ["Adulterated", "Misbranded", "Unapproved", "Counterfeit"], a: 1 },
  { id: 14, q: "A prescription drug is not packaged in a child-resistant container as required by the PPPA. This drug is legally:", o: ["Adulterated", "Misbranded", "Recalled", "Dangerous"], a: 1 },
  { id: 15, q: "During which phase of a clinical trial is the drug first tested in a small group (20-80) of healthy volunteers to focus on safety?", o: ["Phase 1", "Phase 2", "Phase 3", "Phase 4"], a: 0 },
  { id: 16, q: "Which phase of a clinical trial involves 12-300 people and focuses on whether the drug is effective in people with a specific condition?", o: ["Phase 1", "Phase 2", "Phase 3", "Phase 4"], a: 1 },
  { id: 17, q: "If an OTC drug is dispensed pursuant to a prescription, which labeling rules must the pharmacist follow?", o: ["The OTC \"Drug Facts\" panel requirements", "The Prescription drug labeling requirements", "Both OTC and Rx requirements", "Neither, as long as the NDC is on the label"], a: 1 },
  { id: 18, q: "Which Class of Recall involves a product that has a \"reasonable probability of causing severe injury or death\"?", o: ["Class I", "Class II", "Class III", "Class IV"], a: 0 },
  { id: 19, q: "Failure to provide a Patient Package Insert (PPI) for an Estrogen-containing product results in the drug being:", o: ["Adulterated", "Misbranded", "Repossessed", "Unsafe"], a: 1 },
  { id: 20, q: "A MedGuide is required for all of the following EXCEPT:", o: ["NSAIDs", "Antidepressants in children/teens", "Amoxicillin", "Opioids"], a: 2 },
  { id: 21, q: "In an NDC number (e.g., 12345-678-90), the first segment identifies the:", o: ["Drug and Strength", "Package Size", "Labeler (Manufacturer)", "Expiration Date"], a: 2 },
  { id: 22, q: "According to the PPPA, who can make a \"blanket request\" that all future prescriptions be dispensed in non-safety caps?", o: ["The Prescriber", "The Pharmacist", "The Patient", "The Patient's Spouse"], a: 2 },
  { id: 23, q: "Which of the following drugs is EXEMPT from the Poison Prevention Packaging Act?", o: ["Prednisone tabs containing 150mg per package", "Sublingual Nitroglycerin", "High-potency Vitamins", "Liquid Ibuprofen"], a: 1 },
  { id: 24, q: "Under HIPAA, a pharmacy must provide a patient with access to their PHI within how many days of a request?", o: ["15 days", "30 days", "60 days", "90 days"], a: 0 },

  // Set 2: Compounding & Supply Chain Security (Q25-45)
  { id: 25, q: "A pharmacy that compounds pursuant to a patient-specific prescription and is regulated primarily by the state board is known as a:", o: ["503A Pharmacy", "503B Outsourcing Facility", "Class B Pharmacy", "CGMP Facility"], a: 0 },
  { id: 26, q: "If a pharmacy does NOT have a Memorandum of Understanding (MOU) with the FDA, what is the maximum percentage of compounded scripts they can ship interstate?", o: ["5%", "10%", "20%", "50%"], a: 0 },
  { id: 27, q: "The Drug Quality and Security Act of 2013 was passed primarily in response to which event?", o: ["The Sulfanilamide tragedy", "The 2012 fungal meningitis outbreak", "Increased online pharmacy fraud", "Opioid diversion"], a: 1 },
  { id: 28, q: "A 503B Outsourcing Facility must report serious adverse events to the FDA within how many days?", o: ["24 hours", "7 days", "15 days", "30 days"], a: 2 },
  { id: 29, q: "Under the DSCSA, the \"Standardized Numerical Identifier\" (SNI) on a drug package consists of which two elements?", o: ["Lot number and NDC", "NDC and a unique serial number", "NDC and expiration date", "GTIN and lot number"], a: 1 },
  { id: 30, q: "When investigating \"suspect products\" under DSCSA, a pharmacy must verify the product identifier of at least how many products?", o: ["1 product or 5%", "3 products or 10% (whichever is greater)", "All products in the lot", "10 products or 50%"], a: 1 },
  { id: 31, q: "Providing a drug to someone other than the consumer is \"distributing.\" Which of the following is an EXCEPTION to needing a wholesale distribution license?", o: ["Selling $50,000 worth of stock to a neighboring pharmacy", "Providing a product to another dispenser on a patient-specific basis", "Selling drugs to a local doctor for general office use in bulk", "Exporting drugs to a partner in Mexico"], a: 1 },
  { id: 32, q: "A drug is considered adulterated if its strength differs from the label. Is it also considered misbranded?", o: ["Yes, it is both", "No, it is only adulterated", "No, it is only misbranded", "Only if the strength is higher than labeled"], a: 0 },
  { id: 33, q: "A manufacturer label for a prescription drug is missing the \"Name and Address of the Manufacturer.\" This drug is:", o: ["Adulterated", "Misbranded", "Recalled", "Unsafe"], a: 1 },
  { id: 34, q: "A pharmacist dispenses a medication but fails to satisfy the REMS requirements for that drug. This is a violation of:", o: ["Adulteration", "Misbranding", "Anti-Kickback Statute", "PDMA"], a: 1 },
  { id: 35, q: "A pharmacist fills a prescription with a manufacturer bottle that is expired, but the BUD they write on the vial is still in the future. This drug is:", o: ["Adulterated only", "Misbranded only", "Both Adulterated and Misbranded", "Legal as long as the drug hasn't changed color"], a: 2 },
  { id: 36, q: "A pharmacy is using a counting tray that has residue from a previous medication. A drug counted on this tray is now:", o: ["Adulterated", "Misbranded", "Substandard", "Counterfeit"], a: 0 },
  { id: 37, q: "OTC medications that are not in \"tamper-resistant\" packaging are considered:", o: ["Adulterated only", "Misbranded only", "Both Adulterated and Misbranded", "Neither, provided the seal is still intact"], a: 2 },
  { id: 38, q: "Which of the following is NOT required on a manufacturer's OTC label?", o: ["Name and address of manufacturer", "Adequate directions for use", "The \"Drug Facts\" panel", "The patient's name"], a: 3 },
  { id: 39, q: "If a pharmacy distributes \"minimal quantities\" of a drug to a licensed physician for office use, is this considered wholesale distribution?", o: ["Yes, always", "No, this is a permitted exception", "Only if the drug is a controlled substance", "Only if the drug is an injectable"], a: 1 },
  { id: 40, q: "A drug container is composed of a poisonous substance that may contaminate the contents. Even if the drug is currently pure, it is legally:", o: ["Adulterated", "Misbranded", "Unapproved", "Class III Recall"], a: 0 },
  { id: 41, q: "Which of the following information is OPTIONAL on an OTC \"Drug Facts\" panel?", o: ["Active ingredients", "Purpose", "Questions? followed by a phone number", "Warnings"], a: 2 },
  { id: 42, q: "A facility that compounds sterile drugs and is exempt from \"track and trace\" provisions because it registers with the FDA is a:", o: ["503A", "503B", "Class A-S", "Hospital pharmacy"], a: 1 },
  { id: 43, q: "A drug recall involving products that could pose a \"moderate danger\" or \"temporary adverse health events\" is:", o: ["Class I", "Class II", "Class III", "Class IV"], a: 1 },
  { id: 44, q: "If a drug is an \"imitation\" of another drug, it is legally:", o: ["Adulterated", "Misbranded", "A biosimilar", "A therapeutic equivalent"], a: 1 },
  { id: 45, q: "Under DSCSA, Transaction History (TH) must include every prior transaction back to the:", o: ["Last 5 years", "Manufacturer", "First wholesaler", "Previous pharmacy"], a: 1 },

  // Set 3: Controlled Substances & Scheduling (Q46-70)
  { id: 46, q: "Under the DEA, a substance with a high potential for abuse, no currently accepted medical use, and a lack of safety data is classified as:", o: ["Schedule I", "Schedule II", "Schedule III", "Schedule IV"], a: 0 },
  { id: 47, q: "Which of the following is a Schedule I substance?", o: ["Cocaine", "Methamphetamine", "Marijuana", "Pentobarbital"], a: 2 },
  { id: 48, q: "Per Texas Law and the DEA, which schedule is Pentobarbital (oral) and Cocaine?", o: ["Schedule I", "Schedule II", "Schedule III", "Schedule IV"], a: 1 },
  { id: 49, q: "Fiorinal (Butalbital/Aspirin/Caffeine) is classified as a Schedule III, while Fioricet (Butalbital/APAP/Caffeine) is:", o: ["Schedule II", "Schedule III", "Schedule IV", "Exempt (Non-controlled) in Texas"], a: 3 },
  { id: 50, q: "Alprazolam, Carisoprodol, and Tramadol are all examples of which schedule?", o: ["Schedule II", "Schedule III", "Schedule IV", "Schedule V"], a: 2 },
  { id: 51, q: "Lyrica (Pregabalin) and Robitussin AC (Codeine/Guaifenesin) are examples of:", o: ["Schedule III", "Schedule IV", "Schedule V", "Dangerous Drugs"], a: 2 },
  { id: 52, q: "In Texas, a compounded narcotic (e.g., Codeine or Opium) that is NOT compounded with a non-narcotic is ALWAYS:", o: ["Schedule II", "Schedule III", "Schedule IV", "Schedule V"], a: 0 },
  { id: 53, q: "A pharmacy may compound a controlled substance pursuant to a prescription as long as the narcotic concentration does not exceed:", o: ["5%", "10%", "20%", "50%"], a: 2 },
  { id: 54, q: "What is the Texas Schedule V limit for Opium?", o: ["50mg/100ml", "100mg/100ml", "200mg/100ml", "500mg/100ml"], a: 0 },
  { id: 55, q: "A compounded liquid contains 75mg of Opium per 100ml. Under Federal law, this is a C-V. Under Texas law, what schedule is it?", o: ["Schedule II", "Schedule III", "Schedule IV", "Schedule V"], a: 1 },
  { id: 56, q: "What are the Schedule III limits for Codeine?", o: ["200mg/100ml", "1.8g/100ml and 90mg/dosage unit", "500mg/100ml", "50mg/100ml"], a: 1 },
  { id: 57, q: "A compounded narcotic prescription will NEVER be classified in which schedule?", o: ["Schedule II", "Schedule III", "Schedule IV", "Schedule V"], a: 2 },
  { id: 58, q: "How often must a \"Dispenser\" (Pharmacy or Practitioner) renew their DEA registration?", o: ["Annually", "Every 2 years", "Every 3 years", "Every 5 years"], a: 2 },
  { id: 59, q: "A DEA registration number for a Mid-level Practitioner (PA or APRN) begins with which letter?", o: ["A", "B", "F", "M"], a: 3 },
  { id: 60, q: "To verify a DEA number (e.g., AB1234563), what is the second step of the math process?", o: ["Add the 1st, 3rd, and 5th digits", "Add the 2nd, 4th, and 6th digits, then multiply by 2", "Add all digits and divide by 9", "Multiply the 7th digit by 3"], a: 1 },
  { id: 61, q: "Which DEA Form is used for INITIAL registration as a Dispenser (Pharmacy)?", o: ["DEA Form 106", "DEA Form 222", "DEA Form 224", "DEA Form 363"], a: 2 },
  { id: 62, q: "Which of the following is NOT required to register with the DEA?", o: ["A pharmacist working at a licensed pharmacy", "A common carrier (UPS/FedEx)", "An ultimate user (patient) with a valid Rx", "All of the above are exempt from personal registration"], a: 3 },
  { id: 63, q: "A hospital assigns a specific internal code to a resident physician to use the hospital's DEA number. This code is written as:", o: ["A prefix to the DEA number", "A suffix to the DEA number (e.g., AP1234563-10)", "A separate 4-digit PIN", "On the back of the prescription only"], a: 1 },
  { id: 64, q: "Upon the sale of a pharmacy, the new owner may use the previous owner's DEA registration for a maximum of how many days?", o: ["10 days", "30 days", "45 days", "60 days"], a: 2 },
  { id: 65, q: "Which form is used to order Schedule II controlled substances?", o: ["DEA Form 41", "DEA Form 106", "DEA Form 222", "DEA Form 224"], a: 2 },
  { id: 66, q: "How many lines are available on a single DEA Form 222?", o: ["10", "15", "20", "Unlimited"], a: 2 },
  { id: 67, q: "If a supplier cannot fill a complete Schedule II order on a DEA Form 222, they have how many days to supply the balance?", o: ["30 days", "45 days", "60 days", "90 days"], a: 2 },
  { id: 68, q: "When ordering Schedule IIs via CSOS (electronic), the digital certificate must be renewed:", o: ["Annually", "Every 2 years", "Every 3 years (with DEA registration)", "It never expires"], a: 2 },
  { id: 69, q: "A pharmacy discovers a \"significant loss\" of controlled substances. Within what timeframe must they notify the DEA?", o: ["Immediately upon discovery", "Within 1 business day in writing", "Within 15 days", "Within 45 days"], a: 1 },
  { id: 70, q: "Which form is used to report the theft or significant loss of controlled substances to the DEA?", o: ["DEA Form 41", "DEA Form 106", "DEA Form 107", "DEA Form 222"], a: 1 },

  // Set 4: Prescriptions, Staffing & PMP (Q71-90)
  { id: 71, q: "In Texas, a Schedule II prescription must be filled within how many days of the date it was issued?", o: ["21 days", "30 days", "60 days", "90 days"], a: 1 },
  { id: 72, q: "A prescriber may issue multiple Schedule II prescriptions for the same patient at once, provided they do not exceed a total of how many days' supply?", o: ["30 days", "60 days", "90 days", "180 days"], a: 2 },
  { id: 73, q: "In Texas, an opioid prescription for \"acute pain\" is legally limited to a maximum of:", o: ["3-day supply", "7-day supply", "10-day supply", "14-day supply"], a: 2 },
  { id: 74, q: "Which of the following is NOT required on a written controlled substance prescription in Texas?", o: ["Manual signature of the provider", "Quantity written as both a number and a word", "Patient's DOB or age", "The pharmacist's license number"], a: 3 },
  { id: 75, q: "Under the Ryan Haight Act, a controlled substance prescription via telemedicine generally requires at least how many in-person appointments?", o: ["One", "Two", "Four", "None (during a public health emergency)"], a: 0 },
  { id: 76, q: "Partial fills for a Schedule II controlled substance are valid for how many days from the date the prescription was issued?", o: ["72 hours", "30 days", "60 days", "6 months"], a: 1 },
  { id: 77, q: "Auto-refill programs in Texas are permitted for which schedules of controlled substances?", o: ["Schedule II and III", "Schedule III only", "Schedule IV and V only", "All schedules"], a: 2 },
  { id: 78, q: "A pharmacist must check the Prescription Monitoring Program (PMP) before dispensing which of the following?", o: ["Antibiotics and Antivirals", "Opioids, Benzos, Barbiturates, and Carisoprodol", "Insulin and Oral Hypoglycemics", "All controlled substances except Schedule V"], a: 1 },
  { id: 79, q: "Which of the following patients is EXEMPT from the mandatory PMP check?", o: ["A patient with a broken arm", "A patient with cancer or a terminal illness in hospice", "A patient under the age of 18", "A patient paying cash"], a: 1 },
  { id: 80, q: "A pharmacy must transmit dispensing info for controlled substances to the TSBP (PMP) within:", o: ["Real-time", "1 business day of the fill", "7 days", "15 days"], a: 1 },
  { id: 81, q: "Methadone 40mg tablets can only be sold to which of the following?", o: ["Retail pharmacies", "Hospitals", "Narcotic Treatment Programs", "Licensed practitioners for office use"], a: 2 },
  { id: 82, q: "Which two drugs can be prescribed for opioid addiction outside of a Narcotic Treatment Program (e.g., in an office-based setting)?", o: ["Methadone and Morphine", "Subutex and Suboxone", "Fentanyl and Oxycodone", "Naloxone and Naltrexone"], a: 1 },
  { id: 83, q: "In Texas, a person must be at least how old to purchase products containing Dextromethorphan over the counter?", o: ["16", "18", "21", "There is no age limit for OTC sales"], a: 1 },
  { id: 84, q: "A Texas Therapeutic Optometrist (T) may possess and administer (but not dispense) Cocaine eye drops in what maximum concentration?", o: ["2%", "5%", "10%", "20%"], a: 2 },
  { id: 85, q: "How many vials of Cocaine eye drops may a Therapeutic Optometrist (T) or Glaucoma Specialist (TG) store at one time?", o: ["1 vial", "2 vials", "5 vials", "10 vials"], a: 1 },
  { id: 86, q: "The Texas State Board of Pharmacy (TSBP) consists of 11 members. How many are licensed pharmacists?", o: ["3", "6", "7", "9"], a: 2 },
  { id: 87, q: "How many terms can a member serve on the TSBP?", o: ["One 3-year term", "Two 6-year terms", "One 10-year term", "For life (appointed by the Governor)"], a: 1 },
  { id: 88, q: "Who has the authority to regulate drug wholesalers in Texas?", o: ["Texas State Board of Pharmacy (TSBP)", "Texas Department of State Health Services (DSHS)", "The DEA", "The FDA"], a: 1 },
  { id: 89, q: "A pharmacy intern requires 1,500 total hours for licensure. How many hours can be completed in a single week?", o: ["40 hours", "50 hours", "60 hours", "Unlimited"], a: 1 },
  { id: 90, q: "A preceptor must have how much experience before they can supervise an intern?", o: ["1 year of experience or 6 months of residency", "3 years of experience", "5 years of experience", "They only need a valid license"], a: 0 },
];
